'use client';

// This file is automatically generated. Do not modify it.
// For more details, see "Firebase Usage Instructions" in the panel to the right.

import { useFirebase } from '../provider';

export function useFirestore() {
  const context = useFirebase();
  if (!context) {
    throw new Error('useFirestore must be used within a FirebaseProvider');
  }
  return context.firestore;
}
